#!/bin/bash

source .functions


echo "Display a boxed scale"
echo "---------------------"

instrument=`cat .instrument`

chooseScale

echo -n "Enter the root note : "
read root

cmd="../frettler $instrument box $root $pattern"
execute "$cmd"

