#!/bin/bash

source .functions


echo "Display the chord fingering for a given chord"
echo "---------------------------------------------"

instrument=`cat .instrument`

chooseChord

echo -n "Enter the root note : "
read root

cmd="../frettler $instrument chord $root $chord --easy"
execute "$cmd"

