#!/bin/bash

source .functions
instrument=`cat .instrument`

echo "Lookup a chord by its fingering and display it"
echo "----------------------------------------------"

echo -n "Enter the digits to lookup, all strings, comma separated : "
read digits

cmd="../frettler $instrument find --digits $digits"
execute "$cmd"
