#!/bin/bash

source .functions
instrument=`cat .instrument`

echo "Lookup a chord and display it"
echo "------------------------------------------"

echo "1: lookup by notes"
echo "2: lookup by fingering"
read choice
if [[ $choice == 1 ]]
then
    echo -n "Enter the notes to lookup, comma separated : "
    read notes
    cmd="../frettler $instrument find --notes $notes"
    execute "$cmd"
else
    echo -n "Enter the fingering to lookup, comma separated : "
    read digits
    cmd="../frettler $instrument find --digits $digits"
    execute "$cmd"
fi

