#!/bin/bash


example() {
  echo "------------------------------------------------------------------------------------------------------------------------------"
  echo ""
  echo "$3) $2"
  echo ""
  echo "> $1"
  eval $1
}

declare -a cmds=(
"./frettler guitar horizontal C scale_major=Standard guitar, fretboard view of C Major scale"
"./frettler guitar vertical A chord_maj --chords=Standard guitar, vertical view of A Major chord, with diatonic chords"
"./frettler guitar vertical C chord_maj=Standard guitar, vertical view of C Major arpeggio "
"./frettler guitar vertical A scale_minor -c=Standard guitar, vertical view of A Minor scale, with diatonic chords"
"./frettler bassguitar horizontal C scale_major_pentatonic=Bass guitar, fretboard view of C Major Pentatonic scale"
"./frettler guitar horizontal A scale_minor_pentatonic -s B,E,A,D,G,B,E=Am Pentatonic scale on a 7 string guitar"
"./frettler ukelele horizontal A scale_harmonic_minor=Ukelele, fretboard view of Am Harmonic scale "
"./frettler guitar horizontal C scale_major --intervals=Standard guitar, fretboard view of C Major Scale with intervals"
"./frettler guitar horizontal A scale_minor -i=Again but with abbrev. intervals option, and an Am scale"
"./frettler guitar horizontal C scale_major -im=Standard guitar, fretboard view of C Major Scale with intervals, in 'monochrome'"
"./frettler guitar horizontal C chord_maj=Standard guitar, fretboard view of C Arpeggio"
"./frettler bassguitar horizontal C scale_major_pentatonic=Bass guitar, fretboard view of C Major Pentatonic scale"
"./frettler bassguitar horizontal C scale_major_pentatonic --intervals --frets 17=Bass guitar, fretboard view to 17th fret of C Major Pentatonic Scale, with intervals"
"./frettler banjo horizontal C scale_blues=Banjo, fretboard view of C Blues scale"
"./frettler guitar vertical G chord_maj=Guitar, vertical view of G Major arpeggio"
)

let n=1
for i in "${cmds[@]}"; do
  cmd=${i%=*}
  comment=${i#*=}
  example "$cmd" "$comment" "$n"
  ((n=n+1))
done
