#!/bin/bash


example() {
  echo ""
  echo "> $1"
  eval $1
}

declare -a cmds=(
"./frettler GUITAR HORIZONTAL SCALE C MAJOR_SCALE"
"./frettler GUITAR HORIZONTAL SCALE A MAJOR_SCALE"
"./frettler BASSGUITAR HORIZONTAL SCALE C MAJOR_PENTATONIC_SCALE"
"./frettler GUITAR VERTICAL CHORD G MAJOR_TRIAD"
"./frettler UKELELE HORIZONTAL SCALE C MINOR_PENTATONIC_SCALE"
)

for i in "${cmds[@]}"; do example "$i"; done
